//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCounter
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOOKUP_CODE
    {
        public int SL_NO { get; set; }
        public Nullable<int> LOOKUP_CODE1 { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
