//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCounter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int VendorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public int CreditLimit { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual VendorTransaction VendorTransaction { get; set; }
    }
}
