//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCounter
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTransaction
    {
        public int VendorID { get; set; }
        public int TotalPieces { get; set; }
        public int TotalKgs { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public System.DateTime TxnDate { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
